### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by manimaul** [manimaul/s57tiler#3]
Investigate serving tile data directly rather than using [tileserver-gl](https://github.com/maptiler/tileserver-gl).

The goal is to have the ability to add custom behavior.  For example (#1) could be server side logic rather than complex client side styling rules for each feature. Another example is that we will need the ability to update features, add meta-data and control access based on additional information such as chart publisher. 

We need to serve the following resources:
- style json
- fonts
- sprites & sprite json
- chart view js & html
- mvt

Most of these resources with the exception of chart data could be stored in just about any database or even the file system. The interesting aspect will be serving the geometry data as MVT. For this we could possibly use the PostGIS  [ST_AsMVT](https://postgis.net/docs/ST_AsMVT.html) function. A Postgres / PostGIS relational db will be well suited for managing chart data as we can easily associate chart data with specific chart, publisher and user tables.

Some alternatives to consider: 
- [t-rex](https://t-rex.tileserver.ch/)
- [hecate](https://github.com/mapbox/Hecate)

**Comment by ZoroLH** [comment]
any update??
