### ISSUE TITLE
How to load multiple  .mbtiles

### ISSUE THREAD

**Issue by cust1105** [manimaul/s57tiler#6]
Dear William
  Thank you so much for opening up this project. I tried loading a mbtiles file and it worked. But how to load multiple mbtiles files.

**Comment by alexg-k** [comment]
It is not the prettiest solution, but it works:
`find data/charts/DE11000/ -name *.000 -exec docker run -v $(pwd)/data:/data s57t s57tiler mbtiles -i {} -o /data/{} -n LNDARE,DEPARE,SEAARE,SLCONS,PONTON,HULKES,SOUNDG,BOYSPP`

Afterwards you can try: `tile-join -no-tile-size-limit -o merged.mbtiles *mbtiles`, see [tippcanoe](https://github.com/felt/tippecanoe) for more information.
